#pragma once

#define PROCESS_LIST_REQ "PROCESS_LIST_REQ"
#define PROCESS_LIST "PROCESS_LIST"
#define NEW_PROCESS "NEW_PROCESS"
#define FOCUS_CHANGE "FOCUS_CHANGE"
#define PROCESS_CLOSE "PROCESS_CLOSE"
#define COMMAND "COMMAND"
#define CONNECTION_CLOSED "CONNECTION_CLOSED"
#define FOCUS_CHANGE_REQ "FOCUS_CHANGE_REQ"
#define WINDOW_CLOSE_REQ "WINDOW_CLOSE_REQ"